algoritmo "ParOuImpar"
// =============================================================
// Algoritmo para verificar se um valor e PAR ou IMPAR
// =============================================================
var
N: Inteiro
inicio
Escreva("Digite um numero qualquer: ")
Leia(N)
Se (N % 2 = 0) entao
   EscrevaL("O numero ", N, " e PAR")
senao
   EscrevaL("O numero ", N, " e IMPAR")
FimSe
fimalgoritmo
